[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
voting = "8H7dfzoBA4kJjokGqDgQ4VsDeBqg7SuMWFUWowdvRQda"

[programs.devnet]
voting = "8H7dfzoBA4kJjokGqDgQ4VsDeBqg7SuMWFUWowdvRQda"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/opt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*"

[workspace]
types = "client/types/"
