[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
soltrain_voting_program = "4PGnHfbudx56T214YReyJ25n3UCfLvWG5icWocESzH6n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/opt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*"

[workspace]
types = "types/"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "localhost"
ledger = ".anchor/test-ledger"
rpc_port = 8899
